import { Ban, Loader2, Mail, Search, TriangleAlert } from "lucide-react";
import type { QueueItem } from "../../types/alerts";
import { queueKey } from "../../utils/alerts";

interface Props { ready: QueueItem[]; blocked: QueueItem[]; selected: Set<string>; search: string; onSearchChange: (v: string) => void; onToggle: (item: QueueItem) => void; onToggleAll: () => void; onSendOne: (item: QueueItem) => void; sendingKey: string | null; }
export default function PendingQueue({ ready, blocked, selected, search, onSearchChange, onToggle, onToggleAll, onSendOne, sendingKey }: Props) {
  const term = search.trim().toLowerCase();
  const matches = (item: QueueItem) => [item.name, item.student_number, item.email].some((value) => value?.toLowerCase().includes(term));
  const filteredReady = term ? ready.filter(matches) : ready;
  const filteredBlocked = term ? blocked.filter(matches) : blocked;
  return <section className="overflow-hidden rounded-2xl border border-stone-200 bg-white"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-stone-200 px-5 py-4"><h2 className="flex items-center gap-2 text-base font-semibold text-stone-900"><TriangleAlert className="h-4 w-4 text-red-500" />Pending alert queue ({filteredReady.length} of {ready.length})</h2><div className="flex items-center gap-4"><label className="relative"><Search className="pointer-events-none absolute left-2 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-stone-400" aria-hidden="true" /><input type="search" value={search} onChange={(event) => onSearchChange(event.target.value)} placeholder="Search name, student number or email" className="w-64 rounded-md border border-stone-200 py-1.5 pl-7 pr-2 text-xs" /></label>{filteredReady.length > 0 && <label className="whitespace-nowrap text-xs text-stone-600"><input type="checkbox" checked={filteredReady.every((item) => selected.has(queueKey(item)))} onChange={onToggleAll} className="mr-2" />Select all</label>}</div></header>{filteredReady.length === 0 ? <p className="px-6 py-10 text-center text-sm text-stone-500">{ready.length === 0 ? "Nobody is waiting to be contacted." : "No pending alerts match your search."}</p> : <ul className="divide-y divide-stone-100">{filteredReady.map((item) => { const key = queueKey(item); return <li key={key} className="flex flex-wrap items-center gap-3 px-5 py-3"><input type="checkbox" checked={selected.has(key)} onChange={() => onToggle(item)} aria-label={`Select ${item.name}`} /><div className="min-w-0 flex-1"><p className="font-semibold text-stone-900">{item.name}</p><p className="text-xs text-stone-500">{item.email} · {item.unit_code}</p></div><span className="text-xs font-medium text-stone-600">{item.risk_tier}</span><button type="button" onClick={() => onSendOne(item)} disabled={sendingKey === key} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-3.5 py-2 text-sm font-medium text-white disabled:opacity-50">{sendingKey === key ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Mail className="h-3.5 w-3.5" />}Send alert</button></li>; })}</ul>}{blocked.length > 0 && <details className="border-t border-stone-200 bg-stone-50 px-5 py-3"><summary className="cursor-pointer text-xs font-medium text-stone-600"><Ban className="mr-1 inline h-3.5 w-3.5" />Blocked ({filteredBlocked.length} of {blocked.length})</summary><ul className="mt-3 space-y-2">{filteredBlocked.map((item) => <li key={queueKey(item)} className="text-sm text-stone-700">{item.name}: <span className="text-stone-500">{item.blocked_detail ?? item.blocked_reason}</span></li>)}</ul></details>}</section>;
}
