"""add final_verdicts table

Revision ID: 046435841afd
Revises: 2fb0cc1533cf
Create Date: 2026-07-22 19:45:25.953502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046435841afd'
down_revision: Union[str, Sequence[str], None] = '2fb0cc1533cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('final_verdicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_week', sa.Integer(), nullable=False),
    sa.Column('rule_score_id', sa.Integer(), nullable=False),
    sa.Column('ml_score_id', sa.Integer(), nullable=False),
    sa.Column('final_tier', sa.String(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('review_decision', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ml_score_id'], ['risk_scores.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_score_id'], ['risk_scores.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_verdicts_id'), 'final_verdicts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_final_verdicts_id'), table_name='final_verdicts')
    op.drop_table('final_verdicts')
    # ### end Alembic commands ###
