"""add final_verdicts table

Revision ID: 2fb0cc1533cf
Revises: 96dd9a35ee0c
Create Date: 2026-07-22 19:34:58.388403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb0cc1533cf'
down_revision: Union[str, Sequence[str], None] = '96dd9a35ee0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
