"""Add start_date to units

Revision ID: 2fb9fa009e7d
Revises: a4d20ae4429e
Create Date: 2026-07-02 22:12:49.620086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb9fa009e7d'
down_revision: Union[str, Sequence[str], None] = 'a4d20ae4429e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'start_date')
    # ### end Alembic commands ###
