"""add ingestion_batches table and batch_id on assessment_events

Revision ID: 4c7c4d8af49d
Revises: 8cf28a23d6b4
Create Date: 2026-07-08 11:47:27.118600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7c4d8af49d'
down_revision: Union[str, Sequence[str], None] = '8cf28a23d6b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lecturer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_batches_id'), 'ingestion_batches', ['id'], unique=False)
    op.add_column('assessment_events', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assessment_events', 'ingestion_batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Named explicitly - the auto-generated FK name confirmed via
    # pg_constraint, since op.create_foreign_key(None, ...) in upgrade()
    # left Postgres to pick the name (drop_constraint(None, ...) is not
    # valid and would fail on rollback).
    op.drop_constraint('assessment_events_batch_id_fkey', 'assessment_events', type_='foreignkey')
    op.drop_column('assessment_events', 'batch_id')
    op.drop_index(op.f('ix_ingestion_batches_id'), table_name='ingestion_batches')
    op.drop_table('ingestion_batches')
    # ### end Alembic commands ###