"""add trend_value to assessment_events

Revision ID: 7347c4bf401a
Revises: aed0369b9488
Create Date: 2026-07-22 19:01:09.568128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7347c4bf401a'
down_revision: Union[str, Sequence[str], None] = 'aed0369b9488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_events', sa.Column('trend_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_events', 'trend_value')
    # ### end Alembic commands ###
