"""add is_incomplete and missing_criteria to risk_scores

Revision ID: 7405d54edc00
Revises: 797734305003
Create Date: 2026-07-22 13:10:00.095908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7405d54edc00'
down_revision: Union[str, Sequence[str], None] = '797734305003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_scores', sa.Column('source', sa.String(), nullable=False))
    op.add_column('risk_scores', sa.Column('is_incomplete', sa.Boolean(), nullable=False))
    op.add_column('risk_scores', sa.Column('missing_criteria', sa.String(), nullable=True))
    op.add_column('risk_scores', sa.Column('checkpoint_week', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_scores', 'checkpoint_week')
    op.drop_column('risk_scores', 'missing_criteria')
    op.drop_column('risk_scores', 'is_incomplete')
    op.drop_column('risk_scores', 'source')
    # ### end Alembic commands ###
