"""add level to units

Revision ID: 797734305003
Revises: 11145406aa4b
Create Date: 2026-07-16 17:42:59.390966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797734305003'
down_revision: Union[str, Sequence[str], None] = '11145406aa4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'level')
    # ### end Alembic commands ###
