"""add is_incomplete and missing_criteria to risk_scores

Revision ID: 7f4362f5760b
Revises: 7405d54edc00
Create Date: 2026-07-22 13:31:42.170876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4362f5760b'
down_revision: Union[str, Sequence[str], None] = '7405d54edc00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
