"""add final_verdicts table

Revision ID: 96dd9a35ee0c
Revises: c22ac6cc69bf
Create Date: 2026-07-22 19:32:00.334469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96dd9a35ee0c'
down_revision: Union[str, Sequence[str], None] = 'c22ac6cc69bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
