"""add explanation to risk_scores

Revision ID: 9efa39fe6b74
Revises: 046435841afd
Create Date: 2026-07-22 20:21:07.722066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9efa39fe6b74'
down_revision: Union[str, Sequence[str], None] = '046435841afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_scores', sa.Column('explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_scores', 'explanation')
    # ### end Alembic commands ###
