"""add gender and age to students

Revision ID: 9fc3608872e6
Revises: 441c6046a264
Create Date: 2026-07-16 17:27:23.240740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc3608872e6'
down_revision: Union[str, Sequence[str], None] = '441c6046a264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('students', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'age')
    op.drop_column('students', 'gender')
    # ### end Alembic commands ###
