"""add student_number unique field to students

Revision ID: b722a036152f
Revises: c4ce6f3f048c
Create Date: 2026-07-08 11:32:12.648162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b722a036152f'
down_revision: Union[str, Sequence[str], None] = 'c4ce6f3f048c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('student_number', sa.String(), nullable=False))
    op.create_index(op.f('ix_students_student_number'), 'students', ['student_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_student_number'), table_name='students')
    op.drop_column('students', 'student_number')
    # ### end Alembic commands ###
