"""add max_score to criteria

Revision ID: c371de738933
Revises: b722a036152f
Create Date: 2026-07-08 11:34:41.220392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c371de738933'
down_revision: Union[str, Sequence[str], None] = 'b722a036152f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criteria', sa.Column('max_score', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criteria', 'max_score')
    # ### end Alembic commands ###
