"""add year and teaching_period to units, drop single-column unique on unit_code

Revision ID: c4ce6f3f048c
Revises: f2be9e0ebca3
Create Date: 2026-07-08 10:55:34.108589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ce6f3f048c'
down_revision: Union[str, Sequence[str], None] = 'f2be9e0ebca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('units', sa.Column('teaching_period', sa.String(), nullable=True))
    op.drop_constraint(op.f('units_unit_code_key'), 'units', type_='unique')
    op.create_unique_constraint('uq_unit_code_year_period', 'units', ['unit_code', 'year', 'teaching_period'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_unit_code_year_period', 'units', type_='unique')
    op.create_unique_constraint(op.f('units_unit_code_key'), 'units', ['unit_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('units', 'teaching_period')
    op.drop_column('units', 'year')
    # ### end Alembic commands ###
