"""add unit status field

Revision ID: f2be9e0ebca3
Revises: d7e1e140c600
Create Date: 2026-07-05 19:26:37.629323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2be9e0ebca3'
down_revision: Union[str, Sequence[str], None] = 'd7e1e140c600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'status')
    # ### end Alembic commands ###
